engines:
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "phpmd.xml"
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.php"
exclude_paths:
  - config/**/*
  - examples/**/*
  - public/**/*
  - scripts/**/*
  - storage/**/*
  - tests/**/*
  - "**/vendor/**/*"
