language: php

matrix:
  include:
  - php: 7.2
  - php: 7.3
  - php: nightly
  allow_failures:
  - php: nightly

install: travis_retry composer install --no-interaction --prefer-source

before_script:
  - mysql -e 'create database dbtest;'
  - psql -c 'create database dbtest;' -U postgres

script: vendor/bin/phpunit --configuration phpunit.xml --coverage-clover clover.xml

after_success: bash <(curl -s https://codecov.io/bash)
