<?php
/**
 * Class QueryTestAbstract
 *
 * @created      02.11.2021
 * @author       smiley <smiley@chillerlan.net>
 * @copyright    2021 smiley
 * @license      MIT
 */

namespace chillerlan\DatabaseTest\Query;

use chillerlan\Database\Database;
use chillerlan\Database\Dialects\Dialect;
use chillerlan\Database\Dialects\Firebird;
use chillerlan\Database\Dialects\Postgres;
use chillerlan\Database\Dialects\SQLite;
use chillerlan\Database\Drivers\DriverInterface;
use chillerlan\Database\Query\QueryException;
use chillerlan\Database\ResultInterface;
use chillerlan\DatabaseTest\DBTestAbstract;
use ReflectionClass;
use function array_column;
use function array_values;
use function in_array;
use function json_encode;
use function md5;
use function range;
use function sleep;

abstract class QueryTestAbstract extends DBTestAbstract{

	protected Database $db;
	protected Dialect $dialect;

	const TABLE = 'querytest';

	protected function setUp():void{
		parent::setUp(); // TODO: Change the autogenerated stub

		$this->options->driver = $this->driverFQCN;

		$this->db = new Database($this->options, $this->cache, $this->logger);
		$this->db->connect();

		$this->driver     = $this->db->getDriver();
		$this->dialect    = $this->db->getDialect();
		$this->reflection = new ReflectionClass($this->driverFQCN);

		$this->assertTrue(
			$this->db->create
				->table($this::TABLE)
				->ifNotExists()
				->primaryKey('id')
				->charset('utf8')
				->int('id', 10)
				->varchar('hash', 32)
				->text('data', null, true)
				->field('value', 'decimal', '9,6', null, null, true)
				->field('active', 'boolean', null, null, null, null, null, 'false')
				->field('created', 'timestamp', null, null, null, null, 'CURRENT_TIMESTAMP')
				->query()
		);
	}

	protected function tearDown():void{
		$this->assertTrue($this->db->drop->table($this::TABLE)->ifExists()->query());
		$this->assertTrue($this->db->disconnect());
	}

	public function testInstance():void{
		// of course they are (basically unnecessary since PHP 7.4)
		$this::assertInstanceOf(Database::class, $this->db);
		$this::assertInstanceOf(DriverInterface::class, $this->db);
		$this::assertInstanceOf(Dialect::class, $this->dialect);
	}

	// the following 2 tests don't use type casting to make sure we receive the "correct" types from the underlying driver

	abstract protected function assertInsertResult(ResultInterface $result):void;
	abstract protected function assertInsertMultiResult(ResultInterface $result):void;

	protected function data():array{
		return [
			['id' => 1, 'hash' => md5(1), 'data' => 'foo', 'value' => 123.456, 'active' => 0],
			['id' => 2, 'hash' => md5(2), 'data' => 'bar', 'value' => 123.456789, 'active' => 1],
			['id' => 3, 'hash' => md5(3), 'data' => 'baz', 'value' => 123.456, 'active' => 0],
		];
	}

	public function testInsert():void{

		$insert = $this->db->insert
			->into($this::TABLE)
			->values(['id' => 0, 'hash' => md5(0), 'data' => 'foo', 'value' => 123.456, 'active' => 1])
			->query();

		$this->assertTrue($insert);

		$this->assertInsertResult($this->db->select->from([$this::TABLE])->query());
	}

	public function testInsertMulti():void{

		$this->assertTrue(
			$this->db->insert
				->into($this::TABLE, 'IGNORE', 'id')
				->values($this->data())
				->multi()
		);

		$this->assertInsertMultiResult($this->db->select->from([$this::TABLE])->query());
	}

	public function testSelect():void{

		$this->db->insert
			->into($this::TABLE)
			->values($this->data())
			->multi();

		$q = $this->db->select
			->cols(['id' => 't1.id', 'hash' => ['t1.hash']])
			->from(['t1' => $this::TABLE])
			->offset(1)
			->limit(2)
		;

		$this->assertSame(3, $q->count()); // ignores limit/offset

		$r = $q->query();

		$this->assertSame(2, $r->length);
		$this->assertSame(2, (int)$r[0]['id']);
		$this->assertSame(md5(2), $r[0]['hash']);
		$this->assertSame(md5(3), $r[1]->id('md5'));
		$this->assertSame(md5(3), $r[1]->hash);

		$r = $this->db->select
			->cols(['hash', 'value'])
			->from([$this::TABLE])
			->where('active', 1)
			->query('hash')
		;

		$this->assertSame(
			'{"c81e728d9d4c2f636f067f89cc14862c":{"hash":"c81e728d9d4c2f636f067f89cc14862c","value":"123.456789"}}',
			json_encode($r)
		);

		$r = $this->db->select
			->from([$this::TABLE])
			->where('id', [1, 2], 'in')
			->orderBy(['hash' => 'desc'])
			->query()
		;

		$this->assertSame('bar', $r[0]->data);
		$this->assertSame('foo', $r[1]->data);
		$this->assertTrue((bool)$r[0]->active);
		$this->assertFalse((bool)$r[1]->active);
	}

	public function testUpdate():void{

		$this->db->insert
			->into($this::TABLE)
			->values($this->data())
			->multi();

		$this->assertTrue(
			$this->db->update
				->table($this::TABLE)
				->set([
					'data'   => 'whatever',
					'value'  => 42.42,
					'active' => 1,
				])
				->where('id', 1)
				->query()
		);

		$r = $this->db->select
			     ->cols(['hash', 'data', 'value', 'active'])
			     ->from([$this::TABLE])
			     ->where('id', 1)
			     ->query('hash')
		['c4ca4238a0b923820dcc509a6f75849b'];

		$this->assertSame('whatever', $r->data);
		$this->assertSame(42.42, (float)$r->value);
		$this->assertTrue((bool)$r->active);
	}

	public function testDelete():void{

		$this->db->insert
			->into($this::TABLE)
			->values($this->data())
			->multi();

		$q = $this->db->select->cols(['hash'])->from([$this::TABLE]);

		$this->assertSame([
			'c4ca4238a0b923820dcc509a6f75849b',
			'c81e728d9d4c2f636f067f89cc14862c',
			'eccbc87e4b5ce2fe28308fd9f2a7baf3',
		], array_column($q->query()->__toArray(), 'hash'));

		$this->assertTrue($this->db->delete->from($this::TABLE)->where('id', 2)->query());

		$r = $q->query();

		$this->assertSame(2, $r->length);
		$this->assertSame([
			'c4ca4238a0b923820dcc509a6f75849b',
			'eccbc87e4b5ce2fe28308fd9f2a7baf3',
		], array_column($r->__toArray(), 'hash'));
	}

	public function testSelectCached():void{

		$this->db->insert
			->into($this::TABLE)
			->values([['id' => '?', 'hash' => '?']])
			->callback(range(1, 10), fn($k) => [$k, md5($k)])
		;

		$r           = $this->db->select->from([$this::TABLE])->cached(2);
		$getCacheKey = $this->getMethod('cacheKey');
		$cacheKey    = $getCacheKey->invokeArgs($this->driver, [$r->sql(), [], 'hash']);

		// uncached
		$this->assertFalse($this->cache->has($cacheKey));
		$r->query('hash');

		// cached
		$this->assertTrue($this->cache->has($cacheKey));
		$r->query('hash');

		sleep(2);
#		$this->cache->clear();

		// raw uncached
		$this->assertFalse($this->cache->has($cacheKey));
		$this->db->rawCached($r->sql(), 'hash', true, 1);

		// cached
		$this->assertTrue($this->cache->has($cacheKey));
		$this->db->rawCached($r->sql(), 'hash', true, 1);

		sleep(2);
#		$this->cache->clear();

		// prepared uncached
		$this->assertFalse($this->cache->has($cacheKey));
		$this->db->preparedCached($r->sql(), [], 'hash', true, 1);

		// cached
		$this->assertTrue($this->cache->has($cacheKey));
		$this->db->preparedCached($r->sql(), [], 'hash', true, 1);
	}

	public function testShowDatabases():void{

		$r = $this->db->show
			->databases()
			->query()
			->__toArray();

		$this->logger->debug('SHOW DATABASES:', $r);

		$this->assertTrue(in_array($this->env->get($this->envPrefix.'_DATABASE'), array_column($r, 'Database')));
	}

	public function testShowTables():void{

		$r = $this->db->show
			->tables()
			->query()
			->__toArray();

		$this->logger->debug('SHOW TABLES:', $r);

		foreach($r as $tables){
			[$table] = array_values($tables);

			if($table === $this::TABLE){
				$this->assertSame($this::TABLE, $table);
				break;
			}

		}

	}


	// exceptions galore!

	public function testInvalidStatementException():void{
		$this->expectException(QueryException::class);
		$this->expectExceptionMessage('invalid statement');

		/** @noinspection PhpExpressionResultUnusedInspection */
		$this->db->foo;
	}

	public function testCreateDatabaseNoNameException():void{
		$this->expectException(QueryException::class);
		$this->expectExceptionMessage('no name specified');

		$this->db->create->database('')->sql();
	}

	public function testCreateTableNoNameException():void{
		$this->expectException(QueryException::class);
		$this->expectExceptionMessage('no name specified');

		$this->db->create->table('')->sql();
	}

	public function testDropDatabaseNoNameException():void{
		$this->expectException(QueryException::class);
		$this->expectExceptionMessage('no name specified');

		$this->db->drop->database('')->sql();
	}

	public function testDropTableNoNameException():void{
		$this->expectException(QueryException::class);
		$this->expectExceptionMessage('no name specified');

		$this->db->drop->table('')->sql();
	}

	public function testInsertTableNoNameException():void{
		$this->expectException(QueryException::class);
		$this->expectExceptionMessage('no name specified');

		$this->db->insert->into('')->sql();
	}

	public function testInsertInvalidDataException():void{
		$this->expectException(QueryException::class);
		$this->expectExceptionMessage('no values given');

		$this->db->insert->into('foo')->values([])->sql();
	}

	public function testSelectEmptyFromException():void{
		$this->expectException(QueryException::class);
		$this->expectExceptionMessage('no FROM expression specified');

		$this->db->select->from([])->sql();
	}

	public function testUpdateNoTableException():void{
		$this->expectException(QueryException::class);
		$this->expectExceptionMessage('no name specified');

		$this->db->update->table('')->sql();
	}

	public function testUpdateNoSetException():void{
		$this->expectException(QueryException::class);
		$this->expectExceptionMessage('no fields to update specified');

		$this->db->update->table('foo')->set([])->sql();
	}

	public function testDeleteNoTableException():void{
		$this->expectException(QueryException::class);
		$this->expectExceptionMessage('no name specified');

		$this->db->delete->from('')->sql();
	}

}
